### ISSUE TITLE
DRIVERS

### ISSUE THREAD

**Issue by LuxMiranda** [Cubium/Cubium#42]
- [x] Real-Time Clock
- [x] Gyroscope/Magnetometer
- [x] Temperature
- [x] Analog temperature
- [ ] Boom (wire-cutter)
- [x] Light
- [x] UV
- [ ] Radio
- [x] Battery Voltage 
- [x] Camera 
- [x] Median Filter (software only)
- [x] Aggregator (software only)

**Comment by Sailanarmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finish Drivers](https://trello.com/c/QXTl9wmi/9-finish-drivers)

**Comment by Sailanarmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finish Drivers](https://trello.com/c/QXTl9wmi/9-finish-drivers)

**Comment by Sailanarmo** [comment]
All drivers have code written, they need to be tested more thoroughly once we receive the MCP3008, but all code is finished.
